### PR TITLE
CP-15358: support external ip address setting

### PR DESCRIPTION
**Pull request by Chunjie**
Signed-off-by: Chunjie Zhu <chunjie.zhu@citrix.com>

### CODE REVIEW

**Comment by robhoes** [comment]
Replaces #9.

**Comment by robhoes** [comment]
My final comment on the previous PR has not yet been taken into account: "These are a little odd as defaults... However, after adding the default records (see xcp-idl PR), we can use them: robhoes@8571ed2." (by "odd" I really meant "wrong")

**Comment by Chunjie** [comment]
Hi @robhoes ,

I add your patch.

**Comment by robhoes** [comment]
We only really need the second commit, because it reverts the first. I've created #11 with just the second, and will close this PR.

**Pull request closed without merging**
